### ISSUE TITLE
AzureServiceBus.Send throws an exception

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.AzureServiceBus#6]
```
{
	"ClassName": "System.InvalidOperationException",
	"Message": "Operation is not valid due to the current state of the object.",
	"Data": null,
	"InnerException": null,
	"HelpURL": null,
	"StackTraceString": "   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)\n   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)\n   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)\n   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)\n   at Frends.AzureServiceBus.ServiceBus.<>c__DisplayClass3_0.<<Send>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Frends.AzureServiceBus.ServiceBus.DoQueueSendOperation(String connectionString, String path, TimeSpan timeout, Boolean useCached, Func`2 operation)\n   at Frends.AzureServiceBus.ServiceBus.DoQueueSendOperation(String connectionString, String path, TimeSpan timeout, Boolean useCached, Func`2 operation)\n   at Frends.AzureServiceBus.ServiceBus.Send(SendInput input, SendOptions options, CancellationToken cancellationToken)\n   at Frends.ExecutableProcess.frends_servicebus.frends_servicebus.ExecuteAsync(Object triggerDetails, Object environmentVariables, Object processVariables, Object process, CancellationToken cancellationToken, Func`3 executeSubprocessAsync, Func`3 executeSharedStateCommandAsync, LogLevel logLevel)",
	"RemoteStackTraceString": null,
	"RemoteStackIndex": 0,
	"ExceptionMethod": null,
	"HResult": -2146233079,
	"Source": "Microsoft.Azure.ServiceBus",
	"WatsonBuckets": null
}
```

Same stack as in the error above, but with newlines:
```
at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at Frends.AzureServiceBus.ServiceBus.<>c__DisplayClass3_0.<<Send>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Frends.AzureServiceBus.ServiceBus.DoQueueSendOperation(String connectionString, String path, TimeSpan timeout, Boolean useCached, Func`2 operation)
   at Frends.AzureServiceBus.ServiceBus.DoQueueSendOperation(String connectionString, String path, TimeSpan timeout, Boolean useCached, Func`2 operation)
   at Frends.AzureServiceBus.ServiceBus.Send(SendInput input, SendOptions options, CancellationToken cancellationToken)
   at Frends.ExecutableProcess.frends_servicebus.frends_servicebus.ExecuteAsync(Object triggerDetails, Object environmentVariables, Object processVariables, Object process, CancellationToken cancellationToken, Func`3 executeSubprocessAsync, Func`3 executeSharedStateCommandAsync, LogLevel logLevel)
```

**Comment by MichalFrends1** [comment]
We tried to reproduce the issue, but were unable to do so.
